### ISSUE TITLE
Add support for "enable_stt_selection", "enable_tts_selection", "enable_backend_selection"

### ISSUE THREAD

**Issue by AIIX** [OpenVoiceOS/skill-ovos-setup#29]
Workflow changes ?  

- Option "enable_backend_selection":
  - What pages need to be show once this is disabled ? 
  - How does it affect page selection ? 
  - Voice Process Changes ? 

- Option "enable_tts_selection":
  - Same as above

- Option "enable_stt_selection":
  - Same as above

- Additionally what happens when all three are disabled ? 
  - Setup skill itself should not activate, since there is now no need for setup skill at all ?

**Comment by JarbasAl** [comment]
you are overthinking it, for every option, if not enabled simply skip that step and use default values

skip backend -> just leave whatever already is in mycroft.conf  (same as offline backend)
skip TTS -> just leave whatever already is in mycroft.conf
skip STT -> just leave whatever already is in mycroft.conf

all disabled -> simply goes trough the offline backend route, creates a identity2.json and starts loading skills. will also wait for wifi setup etc before reporting ready

**Comment by JarbasAl** [comment]
have a look at https://github.com/OpenVoiceOS/ovos-backend-client 

it now supports arbitrary number of backends, so in the future we may add even more such as neon and ovos (see open PR for those)

offline still counts as a backend, since it now provides all expected functionality on device, this means you can set your own wolfram keys etc and it will all just work in the skills without changes via the Api classes. Pairing with local backend just means creating a dummy identity2.json file basically
